#!/usr/bin/env bash
# Replace a line with multiple lines with sed

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP' # Port 80
sudo chmod '0777' /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
# Redirect "301 Moved Permanently"
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=dQw4w9WgXcQ permanent;" /etc/nginx/sites-available/default
sudo service nginx restart # systemctl
