#!/usr/bin/env bash
# Install Nginx on a ubuntu server.
# Replace a line with multiple lines with sed.
# make a 404 not found page.
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP' # Firewall Port 80.
sudo chmod '0777' /var/www/html/index.nginx-debian.html
# index file.
echo "Holberton School" > /var/www/html/index.nginx-debian.html
#404 file. --- sudo tee to create the file.
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
# Redirect "301 Moved Permanently".
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=dQw4w9WgXcQ permanent;" /etc/nginx/sites-available/default
sudo sed -i "/listen 80 default_server/a error_page 404 /custom_404.html" /etc/nginx/sites-available/default
sudo service nginx restart # start the server.
