#!/usr/bin/env bash
# This is a initial configuration of a ubuntu server with Nginx.

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP' # Firewall Port 80.
sudo chmod '0777' /var/www/html/index.nginx-debian.html

# index file.
echo "Holberton School" > /var/www/html/index.nginx-debian.html

#404 file. --- sudo tee to create the file.
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Config a response header
sudo sed -i "/listen 80 default_server/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

# Redirect "301 Moved Permanently".
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=dQw4w9WgXcQ permanent;" /etc/nginx/sites-available/default

# Redirect "HTTP 404 error code", not found page
sudo sed -i "/listen 80 default_server/a error_page 404 /custom_404.html;" /etc/nginx/sites-available/default

sudo service nginx restart # start the server.


# To stablish a connection: ssh -i PATH_TO_THE_SSH_KEY_FILE USER
# To make an instruction over the server withoud be inside in it: ssh USER -i PATH_TO_THE_SSH_KEY_FILE 'ls ~/'
# To transfer files to a server: 0x0C-web_server/0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
