#!/usr/bin/env bash
# Install a load balancer (HAproxy)

sudo apt-get update
sudo apt-get -y install haproxy

# Enable HAproxy to be started by the init script
sudo echo "ENABLED=1" >> /etc/default/haproxy

# Set the web front-end and back-end
sudo echo "
frontend web-fronted
	 bind *:80
	 mode http
	 default_backend web-backend

backend web-backend
	balance roundrobin
	server 1645-web-01-1596432707 35.237.133.118:80 check
	server 1645-web-02 3.90.191.97:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
