#!/usr/bin/env bash
# Bash script that display:
    # a message in a infinity loop.
    # a message when receiving a SIGTERM signal.

trap "echo 'I am invincible!!!'" SIGTERM
while :
do
    echo "To infinity and beyond"
    sleep 2
done
