#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd
#display:
#username
#user id
#Home directory path for the user

path="/etc/passwd" #1, 3, 6
while IFS=: read -r line
do
    echo "$line" | cut -f1,3,6 -d ":"
done < "$path"
