#!/usr/bin/env bash
# Bash script that configures host file on docker machine.
#+ Change localhost to 127.0.0.2
#+ Change facebook.com to 8.8.8.8

# sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
echo -e  "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
