#!/usr/bin/env bash
# Script that display all active IPv4

# ifconfig | grep -Po '(?<=inet addr:)[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
# ifconfig | grep -Po 'inet addr:\K\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
ifconfig | grep "inet addr:" | cut -d ":" -f2 | cut -d " " -f1
